Repository kkrt-labs/zk-pig, pull requests merged in 2025-02, with the labels that each got.

#48 📝 Add badges in README
  README.md
Labels: type.docs, type.chore, non-breaking-change

#53 🧑‍💻 Add codecov for coverage reports
  .github/workflows/test.yml
  README.md
Labels: type.devops, non-breaking-change

#57 ✨ Add CLI command `zk-pig config` that returns configuration
  cmd/generate.go
  cmd/root.go
  src/config.go
Labels: type.feat, non-breaking-change, type.feature

#56 📝 Fix typos and improve clarity in documentation
  CONTRIBUTING.md
  README.md
  docs/about-ethereum.md
  docs/prover-input-generation.md
Labels: type.docs, non-breaking-change

#60 🎨 Fix variable name containing typo
  src/ethereum/trie/node_set_test.go
Labels: type.chore, non-breaking-change
