Repository kkrt-labs/zk-pig, pull requests merged in 2025-03, with the labels that each got.

#71 📝 Fix typos in .md files
  docs/modified-mpt.md
  docs/prover-input-generation.md
Labels: type.docs, non-breaking-change

#69 🎨 Fix innacurate function names in docstring
  src/ethereum/evm/executor.go
  src/ethereum/trie/node_set_account.go
Labels: type.chore, non-breaking-change

#70 👷 Bump actions/setup-go from v2 to v5
  .github/workflows/test.yml
Labels: type.devops, non-breaking-change

#81 ✨ Add state access list to prover input
  src/ethereum/state/database_tracker.go
  src/prover-input/input.go
  src/prover-input/proto/input.go
  src/prover-input/proto/input.pb.go
  src/prover-input/proto/input.proto
  src/steps/preflight.go
  src/steps/prepare.go
Labels: type.feat, non-breaking-change, type.feature

#82 📝 Fix typos and grammatical errors in documentation
  docs/prover-input-generation.md
Labels: type.docs, non-breaking-change

#84 📝 Add a link to the README's shield Test
  README.md
Labels: type.docs, non-breaking-change

#87 ✨ Add Prometheus metrics
  docs/metrics.md
  go.mod
  go.sum
  pkg/app/app.go
  pkg/app/app_test.go
  pkg/app/options.go
  src/generator/deamon.go
  src/generator/generator.go
  src/generator/generator_test.go
Labels: type.feat, non-breaking-change, type.feature

#96 🍱 Make zkpig compatible with Pectra
  go.mod
  go.sum
  src/ethereum/trie/node_set.go
Labels: type.chore, non-breaking-change

#97 🔨 Ignore generated in files in test coverage report
  Makefile
Labels: type.devops, non-breaking-change

#88 ✨ Consolidate observability features
  cmd/root.go
  go.mod
  go.sum
  pkg/app/README.md
  pkg/app/app.go
  pkg/app/app_test.go
  pkg/app/flags.go
  pkg/app/options.go
  pkg/app/service.go
  src/app.go
  src/app_test.go
  src/config.go
  src/ethereum/evm/executor_logging.go
  src/ethereum/evm/executor_logging_test.go
  src/flags.go
  src/generator/deamon.go
  src/generator/deamon_test.go
  src/generator/generator.go
  src/generator/generator_test.go
  src/steps/execute.go
  src/steps/preflight.go
  src/steps/prepare.go
  src/store/input_store.go
  src/store/instrument.go
  src/store/instrument_test.go
  src/store/preflight_data_store.go
  src/store/preflight_data_store_test.go
Labels: type.chore, non-breaking-change

#89 🎨 Fix typo in docsting
  src/ethereum/state/database_tracker.go
Labels: type.chore, non-breaking-change

#103 ✨ Add Block Filtering Capability to Generator Daemon
  src/app.go
  src/config.go
  src/flags.go
  src/generator/deamon.go
  src/generator/deamon_test.go
  src/generator/filters.go
  src/generator/filters_test.go
Labels: type.feat, non-breaking-change

#104 💚 Fix Goreleaser Cross version
  Makefile
Labels: type.devops, non-breaking-change

#110 🚑️ Fix Ethereum testnets support
  src/ethereum/chain.go
  src/ethereum/chain_config.go
  src/ethereum/chain_config_test.go
  src/ethereum/chain_test.go
  src/steps/chains.go
  src/steps/preflight.go
Labels: type.fix, non-breaking-change

#111 ⬆️ Bump github.com/kkrt-labs/go-utils from v0.3.3 to v0.3.4
  go.mod
  go.sum
Labels: type.chore, non-breaking-change
